# -*- coding: utf-8 -*-
"""Copy of D12/2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pS9N9bEIA3IeceICdwGP30srxEssXsWf
"""

#We are creating a STREAMLIT WEB APPLICATION

#Deployment are of 2 types
#1.Temporary deployment
#2.Permanent deployment

#Temporary deployment - Local host

!pip install streamlit --quiet #Installing the streamlit library

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py 
# #%%writefile is amagic command to create app.py file
# import streamlit as st
# import joblib
# model = joblib.load('spam-ham')
# st.title('SPAM-HAM CLASSIFIER')#creates a title in web app
# ip = st.text_input('Enter the message') #creates a text box in web app
# op = model.predict([ip])
# if st.button('Predict'):
#   st.title(op[0]) # st.button will create a button with name Predict
#   #st.title(op[0]) # the output will be displayed as a title

#TEMPORARY DEPLOYMENT PART
!streamlit run app.py & npx localtunnel --port 8501
#8501 is the default port number for local tunnel

#Windows + SHIFT + S